theme: jekyll-theme-cayman
title: User-Intended Doppler Measurement Type Prediction Combining CNNs With Smart Post-Processing 
description: Andrew Gilbert, Marit Holden, Line Eikvil, Mariia Rakhmail, Aleksandar Babić, Svein Arne Aase, Eigil Samset, Kristin McLeod
